version: '3.4'

services:
  carvedrock.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development


  carvedrock.app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development


  carvedrock.orderprocessor:
    environment:
      - DOTNET_ENVIRONMENT=Development
